name: 部署到GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 设置GITHUB_TOKEN权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        
      - name: 设置Pages
        uses: actions/configure-pages@v3
        
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
          
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 